# install.packages("dplyr")
# install.packages("readr")
# install.packages("data.table")
# install.packages("stringr")
# install.packages("data.tree")
# install.packages("purrr")
# install.packages("DiagrammeR")
# install.packages("ggformula")
# install.packages("permutations")
# install.packages("Hmisc")
# install.packages("tidyverse")
# install.packages("gdata")

require(tidyverse)
require(dplyr)
require(data.table)
require(stringr)
require(readr)
require(purrr)
require(data.tree)
require(ggformula)
require(permutations)
require(pracma)
require(Hmisc)
require(igraph)
require(modeest)
require(magrittr)

options(digits=22)


